### PR TITLE
retrieve-by-sql: recursively convert nulls to nils

### PR DESCRIPTION
**Pull request by slyrus**
* added convert-nulls-to-nils and list-convert-nulls-to-nils and use
   them in retrieve-by-sql to convert :nulls to nils in lists and arrays

### CODE REVIEW

**Comment by slyrus** [comment]
I should point out that this change is particularly useful with my recent changes to cl-postgres that allow for retrieval of row types -- trivial example is "select row(1,NULL);" which before the cl-postgres change would have yielded the string "{1, NULL}" (or something like that) and without this patch yields ((:row (1 :null))) and with this patch yields ((:row (1 nil))).

**Comment by fukamachi** [comment]
Could you add some test cases for it?

**Comment by slyrus** [comment]
Are there any docs on how to run the tests? (asdf:test-system 'mito) doesn't appear to do much.
thanks!

**Comment by fukamachi** [comment]
Make sure that SQLite3, MySQL & PostgreSQL are installed, and set up them referring to [t/init.sh](https://github.com/fukamachi/mito/blob/master/t/init.sh).

**Comment by slyrus** [comment]
Hmm... can I run the tests without having to install SQLite and MySQL?

**Comment by fukamachi** [comment]
Comment out some lines in mito-test.asd will probably work, like `"db/sqlite3"`, `"db/mysql"`, `"migration/sqlite3"` and `"migration/mysql"`.

**Comment by slyrus** [comment]
Ok, I got all the databases to work, but I don't think mysql and sqlite3 support array types. Do you have a preference for how I organize postgres specific tests? should I put the tests in db/postgres.lisp? make a new db/postgres-test.lisp file? other? thanks!

BTW, the tests were very useful as they uncovered bugs not in mito, but in cl-postgres where I hadn't finished supporting a number of array types. thanks!

**Comment by slyrus** [comment]
Ok, I added some tests. My most recent additions to Postmodern (cl-postgres, really) are needed to make the tests work properly, and since this version is not installed on the travis-ci, these tests are reported as failing.

The version of Postmodern that has the fixes can be found at:

https://github.com/slyrus/Postmodern/tree/text-array-binary-reader

Hopefully these will make it into the main Postmodern trunk quickly.

**Comment by slyrus** [comment]
The required changes to cl-postgres are now in the master branch on github. Can you update the travis-ci system to allow for testing of the branch with the latest cl-postgres? thanks!

**Comment by fukamachi** [comment]
Add a line that installs the latest Postmodern to `.travis.yml`:

```diff
  install:
    # Install Roswell
    - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
    - ros install prove
    - git clone https://github.com/fukamachi/sxql ~/lisp/sxql
+   - ros install marijnh/Postmodern

```

https://github.com/roswell/roswell/wiki/4.1-Travis-CI#installing-the-latest-dependencies

**Comment by slyrus** [comment]
Ok, travis build passes now. Thanks!

**Comment by fukamachi** [comment]
Thanks!

**Pull request merged**
